version: "3.7"

volumes:
  postgres:

networks:
  shared_traefik:
    external: true

x-app-variables: &app-variables
  - DJANGO_DEBUG=off
  - POSTGRES_DB=postgres
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  - POSTGRES_HOST=db
  - POSTGRES_PORT=5432
  - AWS_ACCESS_KEY_ID=
  - AWS_SECRET_ACCESS_KEY=
  - MAILGUN_SENDER_DOMAIN=
  - DJANGO_DEFAULT_FROM_EMAIL=
  - MAILGUN_API_KEY=
  - SENTRY_DSN=

services:
  app:
    image: registry.gitlab.com/{{ cookiecutter.gitlab_project_name }}
    command: /start
    networks:
      - shared_traefik
      - default
    depends_on:
      - db
    environment: *app-variables
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 1
        delay: 0s
        failure_action: rollback
        order: start-first

  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    deploy:
      placement:
        constraints:
          - node.labels.persistent == true
