version: "3.7"

x-prod-variables: &prod-variables
  - DJANGO_SECRET_KEY=
  - DJANGO_ALLOWED_HOSTS=
  - AWS_S3_BUCKET_NAME=

services:
  app:
    environment:  *prod-variables
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.{{ cookiecutter.project_slug }}ProdApp.rule=Host(``) && (PathPrefix(`/admin`) || PathPrefix(`/api`))"
        - "traefik.http.routers.{{ cookiecutter.project_slug }}ProdApp.entrypoints=web"
        - "traefik.http.services.{{ cookiecutter.project_slug }}ProdApp.loadbalancer.server.port=8000"
        - "traefik.docker.network=shared_traefik"
