{% raw -%}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.backend.api.autoscaling.enabled }}
  replicas: {{ .Values.backend.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      {{- include "backend.renderPullSecrets" . | nindent 6 }}
      initContainers:
      {{- include "backend.waitMigrationsInitContainer" . | nindent 6 }}
      containers:
      - name: api
        image: {{ include "backend.image" . }}
        imagePullPolicy: {{ include "backend.imagePullPolicy" . }}
        command:
          - gunicorn
          - {% endraw %}{{ cookiecutter.project_slug }}{% raw %}.wsgi:application
          - -b 0.0.0.0:8000 \
          - --threads
          - 5
        env: {{- include "backend.renderEnv" . | nindent 10 }}
        ports:
          - name: http
            containerPort: {{ .Values.backend.api.service.port }}
            protocol: TCP
        {{- if .Values.backend.api.resources }}
        resources: {{- toYaml .Values.backend.api.resources | nindent 12 }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: /health
            port: http
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: http
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: http
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
{% endraw -%}
