{{ if .Values.pullSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-pullsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "backend.pullSecret" . }}
{{- end }}
