version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.10"
        # [Choice] Install Node.js
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached
      - vscode-extensions:/vscode/.vscode-server/extensions

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      PGPASSWORD: postgres
      EMAIL_URL: smtp://mailhog:1025
      PRE_COMMIT_HOME: "/workspace/.cache/pre-commit"

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 8025:8025

volumes:
  postgres-data:
  vscode-extensions:
