apiVersion: v2
name: "{{ cookiecutter.project_dash }}"
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
- name: common
  version: 1.*.*
  repository: https://charts.bitnami.com/bitnami
- name: postgresql
  version: 11.6.19
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
