domain: ""

backend:
  image:
    repository: ""
    tag: latest
    pullPolicy: IfNotPresent

  debug: "off"
  secretKey: ""
  defaultFromEmail: ""

  s3:
    endpointUrl: "https://storage.yandexcloud.net/"
    accessKey: ""
    secretKey: ""
    bucketName: ""
    publicUrl: ""

  mailgun:
    senderDomain: ""
    apiKey: ""

  sentryDsn: ""
  sentryEnvironment: ""

  databaseUrl: "postgres://{{ cookiecutter.project_dash }}:{{ cookiecutter.project_dash }}@{{ cookiecutter.project_dash }}-postgresql:5432/{{ cookiecutter.project_dash }}"

  api:
    replicaCount: 1

    service:
      port: 8000

    autoscaling:
      enabled: false

    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi

    metrics:
      enabled: true
      serviceMonitor:
        namespace: ""

  waitMigrations:
    resources:
      limits:
        cpu: 1000m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi

  migrations:
    resources:
      limits:
        cpu: 1000m
        memory: 256Mi
      requests:
        cpu: 1000m
        memory: 256Mi

ingress:
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m

postgresql:
  enabled: true
  image:
    tag: 14
  postgresPassword: postgres
  auth:
    postgresPassword: postgres
    username: {{ cookiecutter.project_dash }}
    password: {{ cookiecutter.project_dash }}
    database: {{ cookiecutter.project_dash }}
  primary:
    resources:
      limits:
        memory: 256Mi
        cpu: 250m
      requests:
        memory: 256Mi
        cpu: 250m
    persistence:
      size: 1Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

pullSecret:
  registry: registry.gitlab.com
